...@material-theme
direction: down
grid-columns: 3
grid-gap: 16
publication: Publication lateness {
  class: nested
  release: Scheduled release {class: secondary}
  post: Send starts {class: primary}
  release -> post
}
queue: Queue response {
  class: nested
  post: Send starts {class: primary}
  start: Handler starts {class: primary}
  post -> start
}
handler: Handler duration {
  class: nested
  start: Handler starts {class: primary}
  finish: Handler finishes {class: secondary}
  start -> finish
}
